import { prisma } from '@/lib/prisma'
import { sendMail } from '@/lib/email'
import { getExpiresAt } from './chat-session'

const LEAD_NOTIFICATION_EMAIL =
  process.env.LEAD_NOTIFICATION_EMAIL || 'mi118@mweb.co.za'

interface CreateLeadParams {
  name: string
  phone: string
  email?: string | null
  interestedVehicle?: string | null
  vehicleId?: string | null
  message?: string | null
}

export async function createLead(params: CreateLeadParams) {
  const lead = await prisma.chatLead.create({
    data: {
      name: params.name,
      phone: params.phone,
      email: params.email || null,
      interestedVehicle: params.interestedVehicle || null,
      vehicleId: params.vehicleId || null,
      message: params.message || null,
      expiresAt: getExpiresAt(),
    },
  })

  await sendLeadEmail(lead.id)

  return lead
}

async function sendLeadEmail(leadId: string) {
  try {
    const lead = await prisma.chatLead.findUnique({ where: { id: leadId } })
    if (!lead) return

    const vehicleText = lead.interestedVehicle
      ? ` - ${lead.interestedVehicle}`
      : ''

    const subject = `New Chatbot Lead${vehicleText} - A-Z Truck Sales`

    const html = `
      <h2>New Chatbot Lead</h2>
      <table style="border-collapse:collapse;width:100%;max-width:600px;font-family:sans-serif;">
        <tr><td style="padding:8px 12px;background:#f5b800;color:#111;font-weight:700;">Field</td><td style="padding:8px 12px;background:#f5b800;color:#111;font-weight:700;">Value</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #ddd;">Name</td><td style="padding:8px 12px;border:1px solid #ddd;">${lead.name}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #ddd;">Phone</td><td style="padding:8px 12px;border:1px solid #ddd;">${lead.phone}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #ddd;">Email</td><td style="padding:8px 12px;border:1px solid #ddd;">${lead.email || 'N/A'}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #ddd;">Vehicle</td><td style="padding:8px 12px;border:1px solid #ddd;">${lead.interestedVehicle || 'N/A'}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #ddd;">Message</td><td style="padding:8px 12px;border:1px solid #ddd;">${lead.message || 'N/A'}</td></tr>
      </table>
      <p style="margin-top:16px;font-size:12px;color:#888;">Generated by A-Z Truck Sales Chatbot</p>
    `

    await sendMail({
      subject,
      html,
      to: LEAD_NOTIFICATION_EMAIL,
    })

    await prisma.chatLead.update({
      where: { id: leadId },
      data: { emailSent: true, emailError: null },
    })
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : 'Unknown email error'

    await prisma.chatLead.update({
      where: { id: leadId },
      data: { emailError: errorMessage },
    })
  }
}

export async function resendLeadEmail(leadId: string) {
  await sendLeadEmail(leadId)
  const lead = await prisma.chatLead.findUnique({ where: { id: leadId } })
  return lead
}

export async function getLeads(params: {
  search?: string
  status?: string
  page?: number
  pageSize?: number
}) {
  const { search, status, page = 1, pageSize = 20 } = params

  const where: Record<string, unknown> = {}

  if (status && ['NEW', 'CONTACTED', 'QUALIFIED', 'CLOSED'].includes(status)) {
    where.status = status
  }

  if (search) {
    where.OR = [
      { name: { contains: search, mode: 'insensitive' } },
      { phone: { contains: search } },
      { email: { contains: search, mode: 'insensitive' } },
      { interestedVehicle: { contains: search, mode: 'insensitive' } },
    ]
  }

  const [leads, total] = await Promise.all([
    prisma.chatLead.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
    prisma.chatLead.count({ where }),
  ])

  return { leads, total, page, pageSize }
}

export async function getLeadById(id: string) {
  return prisma.chatLead.findUnique({ where: { id } })
}

export async function updateLeadStatus(
  id: string,
  status: 'NEW' | 'CONTACTED' | 'QUALIFIED' | 'CLOSED',
) {
  return prisma.chatLead.update({
    where: { id },
    data: { status },
  })
}

export async function deleteLead(id: string) {
  return prisma.chatLead.delete({ where: { id } })
}
